routes/main.py
from flask import Blueprint, render_template, request, flash, session, url_for, redirect
from extensions import current_year
from operations.messenger import send_email


main = Blueprint('main', __name__, static_folder='static', template_folder='templates')


@main.route('/', methods=['GET', 'POST'])
def home():
    return render_template('index.html', current_year=current_year)


@main.route('/contact', methods=['GET', 'POST'])
def contact():

    if request.method == 'POST':
        name = request.form.get('name')
        email = request.form.get('email')
        email2 = request.form.get('email2')
        msg = request.form.get('message')
        message = f'{msg}\n\n\nSENDER DETAILS:\nName: {name}\nEmail: {email}\n'

        success_msg = (f'Dear {name},\n\nThanks for sending me a message.\nI will get back to you as soon as possible. '
                       f':)\n\n\nShwetabh Suman\nConcept Artist & Illustrator\nNew Delhi, India')

        if email == email2:
            send_email('IMPORTANT!! - Illustrations Portfolio', ['shwetabhartist@gmail.com'], email, message, '', '')
            send_email('MESSAGE SENT - Shwetabh Suman', [email], 'shwetabhartist@gmail.com', success_msg, '', '')
            flash('Message sent successfully!', 'success')
        else:
            flash("The email doesn't match!", "error")
            return redirect(request.url)
    return render_template('contact.html', current_year=current_year)

routes/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Shwetabh Suman</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/styles.css')}}"
    />
    <link rel="shortcut icon" href="{{ url_for('static', filename='Logo_promotion_writart_tiny.ico') }}">

    {% block style %}
    {% endblock %}

  </head>

  <body>

  <header>
    <div id="brand"><a href="/">SHWETABH SUMAN</a></div>
    <nav>
      <ul>
        <li><a href="https://shwetabhsuman.com" target="_blank">Complete Portfolio</a></li>
        <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
      </ul>
    </nav>
    <div id="hamburger-icon" onclick="toggleMobileMenu(this)">
      <div class="bar1"></div>
      <div class="bar2"></div>
      <div class="bar3"></div>
      <ul class="mobile-menu">
        <li><a href="https://shwetabhsuman.com" target="_blank">Complete Portfolio</a></li>
        <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
      </ul>
    </div>
  </header>

  {% block content %}
  {% endblock %}

  <div id="footer">
      <div id="copyright">
        <p>&#169 {{ current_year }} | illustrations.shwetabhsuman.com | All rights reserved | Any sort of infringement may attract legal consequences.</p>
      </div>
  </div>
  </body>
  <script src="{{ url_for('static', filename='js/base.js')}}"></script>
</html>

routes/templates/contact.html
{% extends "base.html" %}
{% block content %}
<style>
    #contact-bg {
        background: url(static/images/contact/cover.jpg) center center no-repeat;
        background-size: cover;
    }
    #contact-bg form {
        background: rgba(0, 0, 0, 0.5);
        padding: 2% 5% 5% 5%;
    }

</style>
<div style="width:100%;">
    <div class="full-page-form-container form-main" id="contact-bg">
        <form action="{{ url_for('main.contact') }}" method="post">
            <p class="heading-large white-color text-center">DROP A MESSAGE</p>
            <input type="text" name="name" placeholder="Name">
            <input type="email" name="email" placeholder="Email">
            <input type="email" name="email2" placeholder="Please Retype Email">
            <textarea name="message" placeholder="Message"></textarea>
            <button class="btn-1" type="submit">SEND MESSAGE</button>
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                  <div class="{{category}}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        </form>
        <a class="btn-1 whatsapp text-center" href="https://wa.link/qyhvtj" target="_blank">CHAT ON WHATSAPP</a>
    </div>
</div>


{% endblock %}

routes/templates/index.html
{% extends "base.html" %}
{% block content %}

<style>
    .gallery-full-width {
        width:100%;
        background: black;
    }
    .gallery-full-width img {
        padding-bottom: 1%;
    }

    .heading-extra-large {
        background: black;
        color: white;
    }

    @media only screen and (max-width: 600px) {
        pass
    }
    @media only screen and (min-width: 600px) {
        .gallery-full-width {
            width: 85%;
        }
    }
    @media only screen and (min-width: 1280px) {
        .gallery-full-width {
            width: 70%;
        }
    }
</style>
<div style="background: black; padding:2% 2%; display: flex; justify-content: center;">
<!--    <div class="heading-extra-large">-->
<!--        <p class="text-center">CHARACTER CONCEPT</p>-->
<!--    </div>-->
    <div class="gallery-full-width">
        <img src="static/images/illustrations/magicland.jpg" width="100%" loading="lazy">
        <img src="static/images/illustrations/Baba_Bhairav_Dance_sm-f.jpg" width="100%" loading="lazy">
        <div style="display: flex; justify-content: center; width: 100%; padding-bottom: 0.5%;">
            <div style="padding-right:1%;">
                <img src="static/images/illustrations/Shivlinga.jpg" width=" 100%" loading="lazy">
            </div>
            <div>
                <img src="static/images/illustrations/Kamakhya-f.jpg" width="100%" loading="lazy">
            </div>
        </div>
<!--        <img src="static/images/illustrations/Shivlinga.jpg" width="100%" loading="lazy">-->
        <img src="static/images/illustrations/env-2.jpg" width="100%" loading="lazy">
        <img src="static/images/illustrations/env-1.jpg" width="100%" loading="lazy">
<!--        <img src="static/images/illustrations/Kamakhya-f.jpg" width="100%" loading="lazy">-->
        <img src="static/images/illustrations/fantasy-world.jpg" width="100%" loading="lazy">
        <img src="static/images/illustrations/Kedarnath-f.jpg" width="100%" loading="lazy">
        <div style="display: flex; justify-content: center; width: 100%; padding-bottom: 0.5%;">
            <div style="padding-right:1%;">
                <img src="static/images/illustrations/concept-art-practice-f.jpg" width=" 100%" loading="lazy">
            </div>
            <div>
                <img src="static/images/illustrations/only-painting-f.jpg" width="100%" loading="lazy">
            </div>
        </div>
    </div>
</div>
<div style="display: flex; justify-content: center; background:black;">
    <a href="https://shwetabhsuman.com" class="btn-1 text-center heading-medium" target="_blank" style="width:30%; text-decoration:none;">COMPLETE PORTFOLIO</a>
</div>

{% endblock %}